version: '3.9'
services:
  server:
    image: call-count:latest
    environment:
      DATABASE_URL: ecto://phoenix:phoenix@db:5432/phoenix
      SECRET_KEY_BASE: JhhLO9oACpINDgzWo9xBWw+qKCrh7C6tzUhBo4rMGCbB51ssgPzZpkL812d12fL1
    networks:
      - db
      - kafka
    ports: 
      - 4000:4000
    depends_on: 
      - db
      - kafka
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: phoenix
      POSTGRES_USER: phoenix
      POSTGRES_DB: phoenix
    ports: 
      - 5432:5432
    networks:
      - db
    volumes: 
      - db:/var/lib/postgresql/data
  adminer:
    image: adminer
    ports:
      - 8080:8080
    networks:
      - db
  zookeeper:
    hostname: zookeeper
    image: wurstmeister/zookeeper
    expose:
    - "2181"
    ports:
    - "2181:2181"
    networks:
      - kafka
  kafka:
    image: wurstmeister/kafka
    depends_on:
    - zookeeper
    ports:
    - '19092:19092'
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: INTERNAL://kafka:9092,OUTSIDE://kafka:19092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,OUTSIDE://localhost:19092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
    networks:
      - kafka
volumes:
  db:
networks: 
  db:
  kafka: